# Generated by Django 6.0.7 on 2026-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_inquiry_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(max_length=200),
        ),
    ]
